### ISSUE TITLE
recall calculation

### ISSUE THREAD

**Issue by saraperegrina** [amnona/dbbact-examples#2]
Thank you very much for the quick response! I have tried to follow the steps to calculate precision and recall using the data from the get_annotations() endpoint.

I have managed to calculate the precision for each term associated to a sequence, but the recall is not clear to me how to calculate it. For each species I have different sequences associated, so for each associated sequence I try to calculate the recall: the number of annotations associated to each sequence divided by the total number of dbBact annotations containing the term. But this value does not match.

For example, if I search for Prevotella buccae in dbBact.org and look at the term subgingival plaque, I see that the recall is 0.2400. This species is associated to 5 sequences, the sequence whose seqid is 38244, the recall would be = 22/92, but when I calculate this in each sequence and do the average the resulting value is 0,2065. I don't quite understand how to calculate the recall of each term.

Thank you very much again.

_Originally posted by @saraperegrina in https://github.com/amnona/dbbact-examples/issues/1#issuecomment-1565645877_

**Comment by amnona** [comment]
see response for issue #1
